# VacationPy
----

#### Note
* Instructions have been included for each segment. You do not have to follow them exactly, but they are included to help you think through the steps.

In [23]:
# Dependencies and Setup
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import requests
import gmaps
import os

# Import API key
from api_keys import g_key

### Store Part I results into DataFrame
* Load the csv exported in Part I to a DataFrame

In [24]:

cities = pd.read_csv("../output_data/clean_city_data.csv")
cities

,City,City ID,Latitude,Longitude,Humidity (%),Cloudiness (%),Temperature (F),Wind Speed (mph)
0,Port Alfred,964432,-33.59,26.89,73,17,51.19,10.13
1,Mataura,6201424,-46.19,168.86,96,21,50.00,1.99
2,Kapaa,5848280,22.08,-159.32,62,20,83.26,12.75
3,Najrān,103630,17.49,44.13,21,80,84.20,3.24
4,Albany,5106841,42.60,-73.97,40,10,73.00,6.69
...,...,...,...,...,...,...,...,...
599,Upata,3625710,8.01,-62.40,75,63,84.99,1.01
600,Mitú,3674676,1.20,-70.17,82,47,78.76,1.12
601,Siocon,1686123,7.71,122.14,79,87,80.47,4.61
602,Zhangye,1785036,38.93,100.45,36,0,68.92,5.73
603,Anadyr,2127202,64.75,177.48,54,76,57.09,13.42

### Humidity Heatmap
* Configure gmaps.
* Use the Lat and Lng as locations and Humidity as the weight.
* Add Heatmap layer to map.

In [25]:
gmaps.configure(api_key=g_key)
locations = cities[["Latitude", "Longitude"]]
humidity = cities["Humidity (%)"].astype(float)

fig = gmaps.figure()
heat_layer = gmaps.heatmap_layer(locations, weights=humidity, 
                                 dissipating=False, max_intensity=10,
                                 point_radius = 1)
fig.add_layer(heat_layer)
fig

Figure(layout=FigureLayout(height='420px'))

### Create new DataFrame fitting weather criteria
* Narrow down the cities to fit weather conditions.
* Drop any rows will null values.

In [26]:
citiescopy = cities[['City','City ID','Latitude','Longitude','Humidity (%)','Temperature (F)','Wind Speed (mph)']].copy(deep=True)
ideal_cities = citiescopy.loc[(citiescopy["Temperature (F)"] < 90) & (citiescopy["Wind Speed (mph)"] < 10)]
ideal_cities

,City,City ID,Latitude,Longitude,Humidity (%),Temperature (F),Wind Speed (mph)
1,Mataura,6201424,-46.19,168.86,96,50.00,1.99
3,Najrān,103630,17.49,44.13,21,84.20,3.24
4,Albany,5106841,42.60,-73.97,40,73.00,6.69
6,Zeya,2012593,53.75,127.27,58,57.88,3.02
7,Cayenne,3382160,4.93,-52.33,94,78.80,2.24
...,...,...,...,...,...,...,...
598,Portobelo,3702577,9.55,-79.65,78,81.00,8.99
599,Upata,3625710,8.01,-62.40,75,84.99,1.01
600,Mitú,3674676,1.20,-70.17,82,78.76,1.12
601,Siocon,1686123,7.71,122.14,79,80.47,4.61
602,Zhangye,1785036,38.93,100.45,36,68.92,5.73

### Hotel Map
* Store into variable named `hotel_df`.
* Add a "Hotel Name" column to the DataFrame.
* Set parameters to search for hotels with 5000 meters.
* Hit the Google Places API for each city's coordinates.
* Store the first Hotel result into the DataFrame.
* Plot markers on top of the heatmap.

In [43]:
url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"
ideal_cities["Hotel"] = ''
params = {
    'type' : 'lodging',
    "radius" : 5000,
    'key' : g_key
}



for index, row in ideal_cities.iterrows():
    city = row['City']
    longitude = row['Longitude']
    latitude = row['Latitude']
    
    #params['keyword']=city
    params['location']=f'{latitude},{longitude}'
   
    
    hotels = requests.get(url, params=params).json()
    results = hotels['results']
    #print(hotels)
   
    
    try:
        ideal_cities.loc[index, 'Hotel'] = results[0]['name']
    except (KeyError, IndexError):
        print(f"Missing field for {city}, skipping")

C:\Users\Michelle\anaconda3\envs\PythonData\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

C:\Users\Michelle\anaconda3\envs\PythonData\lib\site-packages\pandas\core\indexing.py:966: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.obj[item] = s

Missing field for Albany, skipping
Missing field for Saskylakh, skipping
Missing field for Lavrentiya, skipping
Missing field for Pyaozerskiy, skipping
Missing field for Tokonou, skipping
Missing field for Borogontsy, skipping
Missing field for Chara, skipping
Missing field for Adré, skipping
Missing field for Provideniya, skipping
Missing field for Provideniya, skipping
Missing field for Provideniya, skipping
Missing field for Leningradskiy, skipping
Missing field for Alekseyevsk, skipping
Missing field for Kyra, skipping
Missing field for Berdigestyakh, skipping
Missing field for Berdigestyakh, skipping
Missing field for Berdigestyakh, skipping
Missing field for Saint-Augustin, skipping
Missing field for Tiblawan, skipping
Missing field for Tiblawan, skipping
Missing field for Ostrovnoy, skipping
Missing field for Marzuq, skipping
Missing field for Kasongo-Lunda, skipping
Missing field for Avera, skipping
Missing field for Tiznit Province, skipping
Missing field for Aykhal, skipping
Missing field for Wattegama, skipping
Missing field for Batagay-Alyta, skipping
Missing field for Egvekinot, skipping
Missing field for Shirokiy, skipping
Missing field for Beloha, skipping
Missing field for Shagonar, skipping
Missing field for Shubarkuduk, skipping
Missing field for Murgab, skipping
Missing field for Vladislavovka, skipping
Missing field for Pouébo, skipping
Missing field for Beisfjord, skipping
Missing field for Ust-Kuyga, skipping
Missing field for Ust-Kuyga, skipping
Missing field for Sembakung, skipping
Missing field for Churapcha, skipping
Missing field for Severnyy-Kospashskiy, skipping
Missing field for Pueblo Nuevo, skipping
Missing field for Gazli, skipping
Missing field for Thinadhoo, skipping
Missing field for Bukama, skipping
Missing field for Moba, skipping
Missing field for Dicabisagan, skipping
Missing field for Dicabisagan, skipping
Missing field for Mitú, skipping

In [54]:
# NOTE: Do not change any of the code in this cell

# Using the template add the hotel marks to the heatmap
info_box_template = """
<dl>
<dt>Name</dt><dd>{Hotel}</dd>
<dt>City</dt><dd>{City}</dd>
</dl>
"""
# Store the DataFrame Row
# NOTE: be sure to update with your DataFrame name
hotel_info = [info_box_template.format(**row) for index, row in ideal_cities.iterrows()]
locations = ideal_cities[["Latitude", "Longitude"]]

In [70]:
coord_df = ideal_cities[['Latitude','Longitude']]

figure_layout = {
    'width': '400px',
    'height': '300px',
    'border': '1px solid black',
    'padding': '1px',
    'margin': '0 auto 0 auto'
}
coord = list(coord_df.values)

In [71]:
# Add marker layer ontop of heat map
markers = gmaps.marker_layer(coord)
fig.add_layer(markers)
fig

Figure(layout=FigureLayout(height='420px'))